### ISSUE TITLE
Invisible Tikal Hint Balls and Missing Fire effects?

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#110]
So I was playing through Windy Valley, and noticed something odd when I got to the tornado section. I couldn't find Tikal, even though I know she's in my layouts. I closed and opened the game again, and it still happened. And then I found out that it happens everywhere.
![the invisible woman](https://cloud.githubusercontent.com/assets/26051785/24574392/5b5649ea-1657-11e7-99c8-c554143ed459.png)
Did something happen? Or is it a problem on my end?

Edit: I also noticed that the fiery Orbinauts in Red Mountain and elsewhere did not have any flame effects.
![out of fire](https://cloud.githubusercontent.com/assets/26051785/24574411/d2f60580-1657-11e7-8c6b-0945d8f1b3d4.png)

Edit 2: Flame skulls in the level also breathe invisible fire.

Oh dear...
![cheeseballs](https://cloud.githubusercontent.com/assets/26051785/24574432/2172e7d2-1658-11e7-82d5-e77ee5c4e2c5.png)

Edit 3: Rocket pads don't produce any smoke, giant gear machine in the same level does not produce smoke (which is still broken...can someone look at this? It bugs me), Ice Balls in Ice Cap do not produce frosty air, and the breathing effect from Sonic's mouth does not happen. Basically, I think a lot of particle effects broke...somehow.

Edit 3: Okay....so I went from Windy Valley, to Red Mountain, to Ice Cap, and then to Speed Highway...and now everything's fine.
![tikal reappears](https://cloud.githubusercontent.com/assets/26051785/24574548/1dc280e6-165a-11e7-9948-f69b1ac55fc7.png)
(Don't ask why Tikal is here. I was testing something.)

So...what the heck happened?

Edit 4: It's Emerald Coast. Something in Emerald Coast is causing it. And then something in Speed Highway fixes it.

Edit 5: Never....mind? Ugh. I have no idea what happened with this, and it bothers me.

Edit 6: Actually, I was right! You have to do it when you first start up the game. So, start the game, go to trial mode, and select Emerald Coast as Sonic. Play through Act 2, and when you reach the jump panels, Tikal will be invisible! Speed Highway Act 1 and Final Egg Act 1 fix the problem. This is all I've been able to gather.

And now for something completely off-topic because I'm too lazy to make a new issue for something I just found. Did you know that if you spindash right about here on the stairs at the end of Act 2 of Twinkle Park...
![hidden passage](https://cloud.githubusercontent.com/assets/26051785/24575046/dfaf92be-1661-11e7-9c5e-25f246023574.png)

You'll risk falling right through the level and dying?
![wheee](https://cloud.githubusercontent.com/assets/26051785/24575050/e81b32a0-1661-11e7-82cc-3ea888e980c3.png)

...Ahem. It's a minor collision issue, but I bet it's easily fixable, right?

**Comment by PiKeyAr** [comment]
Are you using the depth peeling branch of the PL mod? It's highly experimental and not intended for regular gameplay.

**Comment by supercoolsonic** [comment]
I'm sorry. ....The what?

**Comment by PiKeyAr** [comment]
The depth-peel branch of the sadx-dc-lighting mod. Also apparently there was a Mod Loader update just recently that broke certain 2D elements, so I guess it's either of those.

**Comment by supercoolsonic** [comment]
...Oh. Probably the mod loader update. I updated it today.

**Comment by PiKeyAr** [comment]
It seems to happen only at certain resolutions/aspect ratios. I'll keep this open until the authors resolve it.

**Comment by PiKeyAr** [comment]
Should be fixed in the ModLoader update that just came out.

**Comment by supercoolsonic** [comment]
Got the update and tested it. ....And it still happens. Tikal was invisible the same way I mentioned above.

**Comment by supercoolsonic** [comment]
Got the new update today, and tested it. It's fixed, but I experience some frame drops. I have the "Resizable Window" feature disabled, so I don't know what's causing it.
