### ISSUE TITLE
Shadow issues in EC Act 2 Pond

### ISSUE THREAD

**Issue by RinMaru** [PiKeyAr/sadx_dreamcast#79]
Allot of flickering on your shadow going on when in the water. I cant really screenshot it since its flickering in and out
![capture](https://cloud.githubusercontent.com/assets/15071652/23836838/03c27976-0755-11e7-8974-171441d8a1ee.PNG)
Shadow is casted on waters surface but not the ground in this area
![capture3](https://cloud.githubusercontent.com/assets/15071652/23836845/2175574a-0755-11e7-882c-b45dcce311d4.PNG)
Rings dont have shadows on the rocks here
![captureq](https://cloud.githubusercontent.com/assets/15071652/23836851/382286e8-0755-11e7-9549-1b87560a545b.PNG)

**Comment by LighteningXL** [comment]
Weird… I don't have that problem. There was a shadow fix for rings, but that only broke the pool water. https://github.com/PiKeyAr/sadx_dreamcast/issues/75
So he reverted it.

**Comment by Zetchzie** [comment]
Im using the latest he uploads to MEGA and the latest modloader.

**Comment by PiKeyAr** [comment]
Sadly this is one of the tradeoffs to restore the proper look of the pond. The Z fighting starts to happen when the bottom of the pond (the wave effect) has a COL flag to enable alpha sorting. It could potentially be fixed by moving the pieces involved, but it's so tightly matched up moving any piece even a little bit would break something else.

**Comment by Zetchzie** [comment]
That pond has been allot of trouble lately it seems, at one point the water robot spawned underground and i had to lead it back into the water. the bubble ripple issue is still present afaik with the latest update.

**Comment by PiKeyAr** [comment]
The bubble ripple issue happens even on the Gamecube, it's probably a sorting/precision error in SADX engine. I've never run into the badnik issue myself, but that might be related to modified SET files. Collision/bounds for the pond haven't been changed for a long time so it isn't coming from changes to the landtable.

**Comment by Zetchzie** [comment]
I think its just the SADX engine goofing at times

**Comment by PiKeyAr** [comment]
This is going to #42 until a proper transparency solution shows up

**Comment by PiKeyAr** [comment]
This may or may not be fixable with depth queue manipulation, so I should take another look at it.

**Comment by PiKeyAr** [comment]
Should be fixed in today's update.
